version: '3.7'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: gptChatBot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "7337:5432"